config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :exes

  resources :countries do
    get 'get_cities', on: :member
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  attr_writer :checked

  def checked
    @checked ||= false
  end

  scope :include_associations, includes(:country)
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, :dependent => :destroy
end

app/models/ex.rb
class Ex < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html, :xml, :json
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all.includes(:country)
    respond_with(@cities)
  end

  def show
    respond_with(@city)
  end

  def new
    @city = City.new
    respond_with(@city)
  end

  def edit
  end

  def create
    @city = City.new(city_params)
    @city.save
    respond_with(@city)
  end

  def update
    @city.update(city_params)
    respond_with(@city)
  end

  def destroy
    @city.destroy
    respond_with(@city)
  end

  private
    def set_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:name, :latitude, :longitude, :country_id)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  respond_to :html, :xml, :json


  def get_cities
    @countries = Country.all
    unless params[:country_ids].nil?
      @cities = City.where(country: params[:country_ids])
      unless params[:cities_ids].nil?
        @checked_cities = City.find(params[:cities_ids]).each { |c| c.checked = true }
        #p @checked_cities
        @cities = ((@checked_cities & @cities) | @cities).sort
      end
      #p @cities
    else
      @cities = []
    end
    respond_to do |format|
      format.html {}
      format.js {}
      format.json { render json: @cities }
    end
  end

  def index
    @countries = Country.all
    respond_with(@countries)
  end

  def show
    respond_with(@country)
  end

  def new
    @country = Country.new
    respond_with(@country)
  end

  def edit
  end

  def create
    @country = Country.new(country_params)
    @country.save
    respond_with(@country)
  end

  def update
    @country.update(country_params)
    respond_with(@country)
  end

  def destroy
    @country.destroy
    respond_with(@country)
  end

  private
    def set_country
      @country = Country.find(params[:id])
    end

    def country_params
      params.require(:country).permit(:name)
    end
end

app/controllers/exes_controller.rb
class ExesController < ApplicationController
  before_action :set_ex, only: [:show, :edit, :update, :destroy]

  def index
    @exes = Ex.all
    respond_with(@exes)
  end

  def show
    respond_with(@ex)
  end

  def new
    @ex = Ex.new
    respond_with(@ex)
  end

  def edit
  end

  def create
    @ex = Ex.new(ex_params)
    @ex.save
    respond_with(@ex)
  end

  def update
    @ex.update(ex_params)
    respond_with(@ex)
  end

  def destroy
    @ex.destroy
    respond_with(@ex)
  end

  private
    def set_ex
      @ex = Ex.find(params[:id])
    end

    def ex_params
      params.require(:ex).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/exes_helper.rb
module ExesHelper
end

app/views/cities/_city.html.slim
tr
  td
    = check_box_tag 'city_ids[]', city.id, checked = city.checked
    = city.name

app/views/cities/_form.html.slim
= simple_form_for(@city) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :latitude
    = f.input :longitude
    = f.association :country

  .form-actions
    = f.button :submit

app/views/cities/edit.html.slim
h1 Editing city

== render 'form'

= link_to 'Show', @city
'|
= link_to 'Back', cities_path

app/views/cities/index.html.slim
h1 Listing cities

table
  thead
    tr
      th Name
      th Latitude
      th Longitude
      th Country
      th
      th
      th

  tbody
    - @cities.each do |city|
      tr
        td = city.name
        td = city.latitude
        td = city.longitude
        td = city.country
        td = link_to 'Show', city
        td = link_to 'Edit', edit_city_path(city)
        td = link_to 'Destroy', city, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New City', new_city_path

app/views/cities/new.html.slim
h1 New city

== render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.slim
p#notice = notice

p
  strong Name:
  = @city.name
p
  strong Latitude:
  = @city.latitude
p
  strong Longitude:
  = @city.longitude
p
  strong Country:
  = @city.country

= link_to 'Edit', edit_city_path(@city)
'|
= link_to 'Back', cities_path

app/views/countries/_country.html.slim
tr
  td
    = check_box_tag 'country_ids[]', country.id
    = country.name

app/views/countries/_form.html.slim
= simple_form_for(@country) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/countries/edit.html.slim
h1 Editing country

== render 'form'

= link_to 'Show', @country
'|
= link_to 'Back', countries_path

app/views/countries/get_cities.html.slim
table
  thead
    tr
      th Cities
  tbody#country_chb
    = render @countries
    /= render @cities unless @cities.nil?
table
  thead
    tr
      th Cities
  tbody#city_chb
    = render @cities unless @cities.nil?

#surrounding
  #first first div
  #second second div
  #third third div

app/views/countries/get_cities.js.erb
$("#city_chb").html("<%= raw escape_javascript(render @cities) %>")

app/views/countries/index.html.slim
h1 Listing countries

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @countries.each do |country|
      tr
        td = country.name
        td = link_to 'Show', country
        td = link_to 'Edit', edit_country_path(country)
        td = link_to 'Destroy', country, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Country', new_country_path

app/views/countries/new.html.slim
h1 New country

== render 'form'

= link_to 'Back', countries_path

app/views/countries/show.html.slim
p#notice = notice

p
  strong Name:
  = @country.name

= link_to 'Edit', edit_country_path(@country)
'|
= link_to 'Back', countries_path

app/views/exes/_form.html.slim
= form_for @ex do |f|
  - if @ex.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ex.errors.count, "error")} prohibited this ex from being saved:"
      ul
        - @ex.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/exes/edit.html.slim
h1 Editing ex

== render 'form'

= link_to 'Show', @ex
'|
= link_to 'Back', exes_path

app/views/exes/index.html.slim
h1 Listing exes

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @exes.each do |ex|
      tr
        td = ex.name
        td = link_to 'Show', ex
        td = link_to 'Edit', edit_ex_path(ex)
        td = link_to 'Destroy', ex, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Ex', new_ex_path

app/views/exes/new.html.slim
h1 New ex

== render 'form'

= link_to 'Back', exes_path

app/views/exes/show.html.slim
p#notice = notice

p
  strong Name:
  = @ex.name

= link_to 'Edit', edit_ex_path(@ex)
'|
= link_to 'Back', exes_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoData</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>